Import the relevant libraries

In [1]:
import numpy as np

Declaring scarlas, vectors and matrices

Scalars

In [2]:
s = 5

In [3]:
s

5

Vectors

In [5]:
v = np.array([5,-2,4])

In [6]:
v

array([ 5, -2,  4])

Matrices

In [8]:
m = np.array([[5,12,6],[-3,0,14]])

In [9]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

Data types

In [11]:
type(s)

int

In [12]:
type(v)

numpy.ndarray

In [13]:
type(m)

numpy.ndarray

In [14]:
s_array = np.array(5)
s_array

array(5)

In [15]:
type(s_array)

numpy.ndarray

Data Shapes

In [16]:
m.shape

(2, 3)

In [17]:
v.shape

(3,)

Creating a column vector

In [18]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [19]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [20]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [21]:
s_array.shape

()