Import the relevant libraries

In [1]:
import numpy as np

Creating a Tensor

In [3]:
m1 = np.array([[5,12,16],[-3,0,14]])
m1

array([[ 5, 12, 16],
       [-3,  0, 14]])

In [4]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [5]:
t = np.array([m1,m2])

In [6]:
t

array([[[ 5, 12, 16],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

Check its shape (rank, row, column) k,m,n

In [7]:
t.shape

(2, 2, 3)

Manually creating a tensor

In [13]:
t_manual = np.array([[[5,12,6],[-3,0,14]],[[9,8,7],[1,3,-5]],[[9,9,9],[10,10,10]]])

In [14]:
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]],

       [[ 9,  9,  9],
        [10, 10, 10]]])

In [15]:
t_manual.shape

(3, 2, 3)

/\\/\\/\\ this tensor is "three, 2x3" arrays.